### ISSUE TITLE
Submit tests.

### ISSUE THREAD

**Issue by Ms2ger** [philipwalton/flexbugs#1]
For a longer-term view, it might be useful to submit the test cases you've constructed to the official test suite at https://github.com/w3c/csswg-test. That tends to encourage browser vendors to fix the issues, and ensures that any new implementations can benefit from your tests—apparently these particular cases were difficult to get right in existing implementations, so new implementations might be at risk of getting them wrong too.

**Comment by philipwalton** [comment]
This is definitely a great suggestion!

For the current bugs I think we're already well-covered in terms of browser vendors being aware of the issues. Most of this information is for present-day development, as I'm sure all these issues will go away in the near future. I know the Chrome teams is aware of the first bug on the list, and @gregwhitworth (co-maintainer of this project with me) works on flexbox at Microsoft, and he assures me all of these issues are fixed in internal builds of IE 12.

As for adding them to the test suite you linked to, when I have some time I'll look around to see if they're not currently represented. Thanks!

**Comment by gregwhitworth** [comment]
@Ms2ger I am meeting up with one of the flex spec editors this week and we can do a quick glance at how the test suite for the new changes are looking and any potential gaps. Also, we have reductions for these bugs so they would be pretty quick to add if need be.

**Comment by Ms2ger** [comment]
Great, thanks folks!

**Comment by gregwhitworth** [comment]
Closing this out as there is nothing further actionable from this.
