### ISSUE TITLE
Layout Vertical Panel 100% 

### ISSUE THREAD

**Issue by christophechevalier** [philipwalton/flexbugs#105]
Hi everyone.

Here is the description of my problem :

I wish my right panel where my <md-tab-body> is displayed 100% vertically ,
and my <sidenav> located in the left panel .

I think I have tested all possible classes of the library to solve my problem but I have doubts about the compatibility with Firefox and Chrome browsers.

If you have a moment to look at my code ...

Here are 2 Screenshots of my main window in Firefox and Chrome:

Firefox :

![firefox_error](https://cloud.githubusercontent.com/assets/7148846/11586401/042c7de4-9a73-11e5-911c-92d54b1a3465.JPG)

Chrome :

![chrome_error](https://cloud.githubusercontent.com/assets/7148846/11586410/177871a0-9a73-11e5-94b6-0ac56b4cbc90.JPG)

Here is a link to my Views of my main window :

https://github.com/petalslink/petals-cockpit/tree/master/public/modules/core/views

ps: Sorry for my bad English speaking ! :)

**Comment by philipwalton** [comment]
Hi @christophechevalier, this repo is not intended to ask Flexbox questions, it's to report browser bugs and their workarounds. If you think you've found a bug, please describe it in detail and I'll reopen the issue. Otherwise, Stack Overflow is a much better place to get questions like this answered.
