### ISSUE TITLE
[IE10] Flexbug #2 fix only works on block elements

### ISSUE THREAD

**Issue by alexmcmillan** [philipwalton/flexbugs#109]
Flexbug 2 refers to [Column flex items set to align-items:center overflow their container](https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container).

The [2.1.b workaround](http://codepen.io/philipwalton/pen/ogYpVv) indicates adding `max-width: 100%` on the flex item causes content to wrap.

This works fine on IE11 for both inline and block elements, but [fails on IE10 inline elements](http://codepen.io/anon/pen/VeeOLd).

[My solution](http://codepen.io/anon/pen/YwwbqO) was to also add `display: block` on the flex item, but I don't know if this will always be possible.. (?)

**Comment by philipwalton** [comment]
In general, width/height declarations don't work on inline elements, so this doesn't surprise me. However, I think the bug is probably that IE10 allows inline display on a flex item in the first place. I believe all flex items are suppose to render block-like (though I'm not 100% sure).

Floated elements are similar to this. If you float an inline element, it renders like a block-level element.
