### ISSUE TITLE
Document the bugs in the Web Platform Docs

### ISSUE THREAD

**Issue by cvrebert** [philipwalton/flexbugs#12]
It would be cool if these bugs were covered in the [Web Platform Docs](https://docs.webplatform.org/wiki/Main_Page).

**Comment by gregwhitworth** [comment]
We discussed similar options to this, but ultimately decided against it. This was due to it being very scoped to helping developers find future compatible techniques for current implementation quirks. Whereas MDN, Web Platform Docs, MSDN and other documentation sites mainlycover what flex is and how it works. Using GH also had the added benefit of other devs doing PR because a good portion of them would already know GH (not to mention @philipwalton and I know it).

Ultimately, I hope this repo doesn't have to exist for very long because the various UAs work together and achieve interop on Flex and make this repo pointless. :)

**Comment by cvrebert** [comment]
Some of those sites do include coverage of browser bugs, although not in as much depth as a dedicated repo. They're reference works, and in what versions of what browsers stuff was broken is useful reference knowledge. I agree about folks having less familiarity with editing the wikis though (not that it's terribly difficult). But scattered sites and blog posts are less discoverable than the big-name web docs wikis, and they are in greater danger of becoming outdated or having uncorrected errors.

**Comment by DavidBruant** [comment]
Hi, I'm an MDN contributor. I agree with the sentiment that these shouldn't be documented as they're very likely to be short term issues.
If an issue becomes long term, it might be worth documenting it, though.

**Comment by cvrebert** [comment]
WPD is dead or a zombie at this point. Long live MDN.
