### ISSUE TITLE
Safari 9: Specifying % for flex-basis when flex-direction=column causes parent to lose height

### ISSUE THREAD

**Issue by runspired** [philipwalton/flexbugs#132]
Bumped into this issue tonight, took a very long time to debug, will circle back with replication bin tomorrow once I sleep.

**Comment by bIbI4k0** [comment]
This problem appears in webkit in some old versions of ios(Chrome for ios is repeat this behavior too).

**Comment by benzen** [comment]
Seams the same for chrome

**Comment by philipwalton** [comment]
Can you please provide an example?

**Comment by runspired** [comment]
@philipwalton sure, only didn't cause I noticed the other related issue.

**Comment by MagmaRules** [comment]
Hi,
Had this bug too. Here is an example: https://jsfiddle.net/b85Lh1q2/1/
Fixed it by adding an extra flex-basis: auto: https://jsfiddle.net/b85Lh1q2/2/

**Comment by mvattuone** [comment]
I had this bug pop up in Safari only. `flex-basis: auto` on my flex items solved it but I do not know why.

**Comment by philipwalton** [comment]
I believe this is just yet another example of Flexbug 1. Since you're setting the flex direction to column, the `flex-basis` value goes in the vertical direction, but the height of the container is determined by its children, so you have a circular reference and a percentage value is meaningless.

However, the items should, by default, not shrink below their minimum content size (Flexbug 1), but in Safari they're not honoring that. When you say `100%`, since the height isn't fixed, that computes to `0`, which is why you're seeing them all squished.

**Comment by jeffreygnatek** [comment]
removing min-height fixed this bug for me in safari.

**Comment by mvattuone** [comment]
Thanks, supremely helpful !

**Comment by selrond** [comment]
Thank you @philipwalton ! You've really helped me!

**Comment by babacardiop** [comment]
Hi, i faced the same bug and the only solution that worked for me was to set an explicit height for my container that have flex-direction:column and target specifically the ipad using media queries:

![image](https://user-images.githubusercontent.com/8863151/34954116-3d3913e6-f9ed-11e7-8e7f-2fffa72684ff.png)

By the way, i don't want to go political, but the fact that you need a mac in order to have dev tools for ipad really sucks. I had to debug stupidly while i could inspect elements even in a windows tablet like surface.... 

https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by nasiamakryg** [comment]
flex-shrink: 0 did the trick for me :)
