### ISSUE TITLE
Chrome/Flexbox Intrinsic Sizing not implemented correctly

### ISSUE THREAD

**Issue by gregwhitworth** [philipwalton/flexbugs#14]
IE12 (Project Spartan) hasn't shipped yet so users [haven't hit this](https://lists.w3.org/Archives/Public/www-style/2015Jan/0449.html) in the wild but it would be good for us to have a work-around. They haven't implemented the update from the flex spec (which will be going to CR soon) regarding intrinsic sizing where you calculate the hypothetical main-size based on the cross-size taking the aspect ratio into account.

**Comment by gregwhitworth** [comment]
Here is the Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=972595)
And here is the Blink [bug](https://code.google.com/p/chromium/issues/detail?id=249112)

**Comment by philipwalton** [comment]
I know it manifests itself differently in different browsers, but I feel like this is similar enough to [flexbug 5](https://github.com/philipwalton/flexbugs#5-column-flex-items-dont-always-preserve-intrinsic-aspect-ratios) that I wonder if it needs its own entry. Perhaps 5 could be refactored to include this issue. What do you think?

**Comment by janfoeh** [comment]
I ran into an issue which to me seems similar, but not quite matching either flexbug 5 or the bugs linked above:

If I define a definite `flex-basis` on a non-stretching flex child with an intrinsic aspect ratio:

    <figure>
      <img src="//placekitten.com/g/300/300" />
      <figcaption>I'm the caption</caption>
    </figure>
    
    figure {
      display: flex;
      align-items: flex-start;
    }
    
    figure img {
      flex: 0 0 150px;
    }

I would expect the image to retain its intrinsic aspect ratio. FF does so, Chrome does not : [demo and screenshots](http://stackoverflow.com/questions/28563384/flex-basis-webkit-blink-ignore-intrinsic-aspect-ratio)

Is this the behaviour you are talking about here? I'm unsure, because the Chrome bug talks about calculating main-size for stretched items with a definite cross size, while the open FF bug seems to apply but does not reflect what I see in FF 35. The [spec change](http://dev.w3.org/csswg/css-flexbox/#min-size-auto) linked to in flexbug 5 also doesn't seem to address this case, unless I misunderstand it, which is quite possible.

**Comment by philipwalton** [comment]
@janfoeh I answered your question on Stack Overflow.
http://stackoverflow.com/questions/28563384/flex-basis-webkit-blink-ignore-intrinsic-aspect-ratio/28773178#28773178

**Comment by gregwhitworth** [comment]
Based on comments from @philipwalton above - I'm closing this out since we cover this pretty well in 5.
