### ISSUE TITLE
IE 11 not shrinking element without flex-basis

### ISSUE THREAD

**Issue by k-lange** [philipwalton/flexbugs#17]
IE 11 (and IE10) are not shrinking elements unless a flex-basis is specified: [Demo](http://codepen.io/anon/pen/RNZbgd)

#### Screenshots

IE 11:
![screen shot 2015-01-27 at 13 34 44](https://cloud.githubusercontent.com/assets/2110524/5918498/a9732f44-a629-11e4-98c4-03566162907d.png)

Chrome:
![screen shot 2015-01-27 at 13 33 51](https://cloud.githubusercontent.com/assets/2110524/5918505/b23495b4-a629-11e4-820e-7f62145098d0.png)

Firefox:
![screen shot 2015-01-27 at 13 33 44](https://cloud.githubusercontent.com/assets/2110524/5918507/b8367086-a629-11e4-969c-8981c7ccca8a.png)

Does anyone know a workaround?

**Comment by philipwalton** [comment]
This is a combination of several things, but mostly its an incarnation of [flexbug 1](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored). Basically, by default items are supposed to have a `min-width` of `auto`, which means they're not supposed to shrink to smaller than their minimum content size.

In your example, you're setting `min-width:0`, which is confusing browsers because it's new to the spec. IE doesn't implement `min-width: auto` and Chrome doesn't implement minimum content sizing, which is why they're both getting this wrong.

I'm going to close this because I'm not sure if it's different enough from the first bug.

**Comment by cletusw** [comment]
Apologies for commenting on an old issue, but flexbug 1 didn't seem to encompass this issue fully for IE 11, and none of the solutions there seemed to help.

I ended up using `-ms-overflow-x: hidden` to fix this, which of course will break any tooltips and whatnot, but by using the `-ms` prefix I'm hoping to contain the damage to IE. It also makes it easier to remove once I no longer need to support IE 11 without worrying about breaking things unintentionally in other browsers.

https://jsbin.com/biqufuladu/1/edit?html,css,output
