### ISSUE TITLE
Bar chart look not working in Safari

### ISSUE THREAD

**Issue by BrianWalters** [philipwalton/flexbugs#180]
Here's my pen:
http://codepen.io/Blargon/pen/dpdrQZ

Works in Chrome, but Safari does not respect the % height. If I use pixels, it does work. I have a hunch that it's related to Flexbug 1, but setting flex-shrink to 0 didn't fix it. I found an alternate solution in the meantime, but it bothers me that I can't figure it out. ¯\_(ツ)_/¯

**Comment by philipwalton** [comment]
I've seen variations of problem like this before where a percentage height wasn't working because the parent element didn't have a declared height (even though the height was definite due to the flex layout algorithm).

I'm not sure of a generic bug or workaround, but in this particular case you can fix this by giving your items a declared height:

```css
.FlexItem {
  height: 100%;
}
```

**Comment by BrianWalters** [comment]
Thanks for your help!
