### ISSUE TITLE
nested flex boxes, when the outer one has a constrained size, result in overlaps instead of scrolling

### ISSUE THREAD

**Issue by v-python** [philipwalton/flexbugs#191]
[Chromium issue 676985](https://bugs.chromium.org/p/chromium/issues/detail?id=676985) seems to me to be different than any described here. While reported on current Chrome, a friend tested with Canary also, and it is still there. Affects Opera and Chrome.  Edge and Firefox do OK. IE is weird, doesn't really support flex very well. No clue about Safari or mobile browsers.

**Comment by SelenIT** [comment]
It seems that it's kind of special case of the [Flexbug #1](../../flexbugs#1-minimum-content-sizing-of-flex-items-not-honored) which seems to not have been completely fixed. It appears that the default `min-height: auto` for flex items of the column-oriented flex containers works incorrectly, as 0, causing the default `flex-shrink:1` shrink the element below its content size. Setting either `min-height: min-content` or (better) `flex-shrink: 0` fixes the issue (so the default `flex-basis: auto`, unlike `min-height: auto` , works properly).

Here is a demo of another problem probably caused by the same root: https://jsfiddle.net/9xzhb6m4/2/
