### ISSUE TITLE
Animated sprite problem 

### ISSUE THREAD

**Issue by BlackMagic** [philipwalton/flexbugs#37]
This is related to issue #29 - Problem with animated sprites. 

I'm redesigning http://ieee-qld.org to be responsive, using flexbox as the basis for the redesign. The original website shows how the sprite is supposed to work.

The code below better reflects the way I want to use animated sprites than the code in issue #29. The sprite is supposed to take up the first 150 pixels of the host flex item. Instead it occupies the entire width of the flex item, ie, 20% of the screen width. The rendering error appears in Win7 with Chrome, FF, Opera and IE11.

I have set up a demo of the problem at http://ieee-qld.org/sprite.

    <!doctype html>
    <html>
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>flex problem</title>
    </head>
    <body>
     <style>
     * {margin:0; padding:0; border:0; outline:0; vertical-align:baseline;}
     body {line-height:1.5; font-size:75%; color:#222; background:#b6d3e4; font-family:"Helvetica Neue", Arial, Helvetica, sans-serif;}
     .sprite {width:150px; height:140px; background-image:url("sprite.jpg");
         -webkit-animation: play 30s steps(6) infinite;
         animation: play 30s steps(6) infinite;}
     @-webkit-keyframes play{from{background-position:0px;}to{background-position:-900px;}}
     @keyframes play{from{background-position:0px;}to{background-position:-900px;}}
     header {display:flex;flex-direction:row;align-items:center; background:#4971a2; position:fixed; left:0px; top:18px; height:25%; width:100%;}
     .box {flex:1;}
     .box:nth-child(2){flex-grow:3;}
     .bold {font-weight:bold;}
     .c {text-align:center;}
     .w  {color:white;}
     h1,h2,h3,h4,h5,h6 {font-weight:normal; color:#111;}
     h1 {font-size:3em; line-height:1; margin-bottom:0.5em;}
    </style>
    <header>
        <div class="box sprite"></div>
        <div class="box"><h1 class="c bold">IEEE Queensland Section</h1></div>
        <div class="box">
           <img src="ieee_logo.png" width="142" height="44" alt="IEEE logo" />
           <p class="w"><br />IEEE is the world's largest<br />professional association for the<br />advancement of technology</p>
         </div>
     </header>
    </body>
    </html>

![sprite](https://cloud.githubusercontent.com/assets/333647/7203204/3f9d6e28-e55c-11e4-804c-a8ac661b65ce.jpg)

![ieee_logo](https://cloud.githubusercontent.com/assets/333647/7203497/7189b1ba-e55e-11e4-9829-9e7738fc31f4.png)

**Comment by BlackMagic** [comment]
![ieee_logo](https://cloud.githubusercontent.com/assets/333647/7203526/9b01e56c-e55e-11e4-98ce-f8b8924317d5.png)

**Comment by gregwhitworth** [comment]
These type of questions are better suited for coding forums such as [StackOverflow](http://stackoverflow.com/). The fact that you have interoperable behavior between all of the browsers means that this is not a flexbox bug that needs to be documented.

**Comment by BlackMagic** [comment]
@gregwhitworth StackOverflow doesn't always have an answer, especially where sprites are involved. See http://stackoverflow.com/questions/29274049/how-to-get-a-fade-transition-on-a-simple-sprite-carousel.

It seems to me that it is a flexbox problem, where all the browsers have made the same mistake, ie, allowing the sprite to occupy the entire flex item's allocated space, ignoring the width specified for the sprite. I'm looking for a workaround, but the only one I can think of involves not using a sprite.

**Comment by BlackMagic** [comment]
@gregwhitworth I have created a different version of the sprite animation, taking out all flexbox references. The sprite works perfectly when not in a flexbox context, ergo, the problem must be flexbox related. Please see http://ieee-qld.org/grid.

**Comment by gregwhitworth** [comment]
Ok, a couple things, I highly recommend sticking to the flex shorthand (as noted in the spec) as flex has quite a complex layout algo and it can be hard to get the exact desired result unless you know exactly which dials to turn. Additionally, removing the box class from your sprite fixes this issue in IE 11, Project Spartan, Chrome and Firefox. This is because you had it set to flex grow and flex shrink via the box class having a flex: 1. Basically, when flexing, if you have flex grow your width initially is used as a min-width, if you don't have flex shrink then it would be a max-width, but you were telling the item to be included in the flexing of the items; thus it flexing beyond the 150px and if you resize your browser very small it will get smaller than 150px. I have updated your code to include a distinct no grow, no shrink, and set flex-basis for the sprite: http://jsbin.com/wapotejoko/1/edit

Let me know if you have any questions.

**Comment by BlackMagic** [comment]
@gregwhitworth Thanks. I see how you've made it work. It's not exactly intuitive, and as you said one needs to know which dials to turn. You've taught me a useful trick not available in any tutorials. Thanks again.

**Comment by gregwhitworth** [comment]
No problem, and I agree it's not the most intuitive, mainly because flex is trying to set both the width or height (depending on flex-direction) but web developers want to initially treat them like regular blocks. So you hit this issue where you're setting a width, but then the browser sees that you want it to flex, so one of those has to fall out, either the width being both the min and max (which would be the case for blocks) or not allow it to flex. Ultimately, I'm glad you got it working. Additionally, I recommend posting these types of questions to stackoverflow and then ping me (twitter: @gregwhitworth | email: gwhit@microsoft.com) and I can work it out there (also, if I can't get to it right away someone else may be able to help out). Thanks, and have a great weekend!!

**Comment by BlackMagic** [comment]
Thanks for the explanation. In my view sprites 'break' the flexbox 
model. Here's why: To get flexbox to display the sprite one frame at a 
time the sprite has to be contained in a space exactly equal to its 
width. The other flex items in the flex container obey the proportional 
spacing rule, but only for the remaining space. This doesn't achieve the 
balanced layout <http://www.ieee-qld.org/> I want to give the <header> 
item.

I can move the sprite further to the right with CSS, covering part of 
the middle flex item, but that disturbs the flexiness of the <header>. I 
will experiment to see if I can place the sprite properly in its flex 
item using JavaScript. If flexbox treated sprites as just another image 
with a fixed width and height, as it has done with the logo in the third 
<header> flex item, there wouldn't be a problem.

**Comment by BlackMagic** [comment]
Solved it! I created a <div class="box"> wrapper around the sprite. Now 
flexbox distributes the three flex items proportionately in the 
container and the sprite shows one frame at a time. I've used CSS to 
right-justify the sprite in the flex item.

     <header>
       <div class="box">
       <div class="sprite"></div></div>
       <div class="box"><h1 class="centre bold">IEEE Queensland 
Section</h1></div>
       <div class="box white">
         <img src="assets/images/ieee_logo.png" width="142px" 
height="44px" alt="IEEE logo" />
         <p><br />IEEE is the world's largest<br />professional 
association for the<br />advancement of technology</p></div>
     </header>

     .sprite {width:140px;
                   height:130px;
                   background-image:url("assets/images/sprite.jpg");
                   position:relative;
                   left:37%;
                   flex: 0 0 140px;
                   -webkit-animation: play 30s steps(6) infinite;
                   animation: play 30s steps(6) infinite;}

**Comment by BlackMagic** [comment]
@gregwhitworth You can see the results at http://ieee-qld.org/grid. I haven't had time to make <header> responsive, but the other parts are, using a combination of flexbox and JavaScript.
