### ISSUE TITLE
Firefox: break-word doesn't work inside flex items

### ISSUE THREAD

**Issue by wilddeer** [philipwalton/flexbugs#39]
**Bug:** `word-wrap: break-word` doesn't work properly inside flex items in Firefox.

**Workaround:** set `min-width: 0` or `overflow-x: hidden` on flex item.

**Demo:** http://codepen.io/wilddeer/pen/BNaXyQ

Tested in Firefox 37.0.1

**Comment by philipwalton** [comment]
This isn't a bug. Firefox is correctly implementing the most recent spec updates (described in [Flexbug 1](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored)). In fact, if you look at your demo in Chrome Canary, you'll see it behaves the same as Firefox.

**Comment by mrflix** [comment]
I'd say it is a bug. Firefox's flex implementation can't cope with single long words.
@wilddeer thanks for the fix!

**Comment by philipwalton** [comment]
It's not a bug. Firefox is correctly implementing `min-width: auto` for flex items. When you change it to `min-width: 0`, you're just using a different value for `min-width` to get your example looking how you want it to look. But both values are being rendered correctly.

**Comment by mrflix** [comment]
So for every flex element that could potentially contain a word longer than the element width I'd have to set the `min-width` to zero?
Because in a web application thats a lot of elements.

**Comment by philipwalton** [comment]
Yes, if you think this isn't ideal, you should bring it up on the [www-style](https://lists.w3.org/Archives/Public/www-style/) mailing list.

**Comment by jpdevries** [comment]
since we're talking about `min-width` and Firefox it might be worth nothing that setting `min-width` OR `max-width` to `fill-available` also yields the desired result. [Codepen](http://codepen.io/jpdevries/pen/Xbgqjz).

```scss
.js-flex.is-fixed {
  .flex__item {
    // any of these should work
    //min-width:0;
    //min-width:fill-available;
    max-width:fill-available;
  }
}
```

##### See also
> __auto__
The default minimum size for flex items, providing a more reasonable default than 0 for other layouts.
 &emsp;&mdash; [min-width MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width)

One thing I don't understand about `min-width:auto` is if it is the default minimum size for flex items then why does `min-width` default to `0px` when not set for flex items? Shouldn't it calculate to auto? The firefox inspector says there is a calculated `min-width` of `0px` yet if we set the `min-width` to `0` or `0px` we get different results...

![](http://j4p.us/image/0s3l3H0c2f35/Screen%20Shot%202015-06-11%20at%203.32.06%20PM.png)
_Computed `min-width` value of a non flex item_

![](http://j4p.us/image/0b0M3q1x2D2M/Screen%20Shot%202015-06-11%20at%203.32.43%20PM.png)
_Computed `min-width` value of a flex item_

**Comment by mrflix** [comment]
Good point @jpdevries.

Chrome sometimes crushes flex content instead of allowing `overflow: scroll`. I suppose a default `min-width: auto` on flex elements fixes that. But why doesn't `min-width: auto` incorporate `word-wrap: break-word;`?

**Comment by jpdevries** [comment]
@mrflix I wish i could tell you. I'm still confused about whether or not, according to the spec, flex items should have a calculated `min-width:auto` if not set. Maybe by 'default minimum size' they mean `flex-basis:auto` which would make more sense. 

It sounds like for your use case you'll need to specify a `min-width` other than `auto` to keep your flex item from growing infinitely. 

IMO It's pretty confusing that saying "always be at least 0 in width" means "don't grow horizontally forever" which is why i think `max-width:fill-available` is more legible.

**Comment by philipwalton** [comment]
@mrflix, you wrote:

> But why doesn't `min-width: auto` incorporate `word-wrap: break-word;`?

Because if it did, the minimum content size would be the width of a single letter, since all words could be broken at any point. `min-width: auto` for text content means the width of the longest word.

@jpdevries you wrote:

> I'm still confused about whether or not, according to the spec, flex items should have a calculated `min-width:auto` if not set.

Yes, the default is `auto` for flex items and `0px` for block elements. It's important to keep in mind that developer tools aren't always accurate.

**Comment by jpdevries** [comment]
@philipwalton thank you for the clarification! if i get around to it, i'll work on reporting the issue with developer tools to applicable vendors

**Comment by trans** [comment]
Not even `min-width` seems to work for me. Unless I can get the words to wrap I will have to go back to tables :sigh:.

```
.grid {
  display: flex;
  flex-flow: row wrap;
  max-width: 1080px;
  margin: 0 auto;
  border: 1px solid gray;
}

.grid > * {
  flex-basis: 15em;
  flex-grow: 2;
}

.grid div {
  border: 1px solid #222;
  height: 320px;
  margin: 1em;
  font-family: sans-serif;
  font-size: 30pt;
  min-width: 0;
}
```

What am I doing wrong?
