### ISSUE TITLE
ordered list with flex in firefox

### ISSUE THREAD

**Issue by nanaya1** [philipwalton/flexbugs#61]
This code: http://codepen.io/anon/pen/jPGzPK

Chrome/IE: list numbers are 1 and 2 (correct?)
Firefox: all 0

**Comment by 7studio** [comment]
Hi,
An issue was already opened for this problem: [Bug 1171419 - ordered list order count broken for flex container](https://bugzilla.mozilla.org/show_bug.cgi?id=1171419).

**Comment by philipwalton** [comment]
Having the tracking bug listed here is good, so if others find this issue they can follow it. I'm going to close this though because there's not a clear workaround other than to just not use a `<ol>` as a flex container, and I think that will be pretty obvious to most people encountering this problem.
