### ISSUE TITLE
flexbox problem with IE11, double flex definition

### ISSUE THREAD

**Issue by BlackMagic** [philipwalton/flexbugs#62]
While updating a large, complex web page I accidentally put in an unnecessary `display:flex` declaration. The page renders fine on webkit browsers but not on IE11. The relevant code is isolated here: https://jsbin.com/rahofib/edit?html,output

Notice ` <section id="main">` wraps around `<div class="ieee">`. Both selectors contain `display:flex; flex-direction:row;` declarations. Webkit gets it right, IE11 produces garbage.

**Comment by philipwalton** [comment]
> I accidentally put in an unnecessary display:flex declaration

When an element with `display: flex` is inside of a block parent, it fills all the available space horizontally (similar to how block items work). But when an element with `display: flex` is inside of another element with `display: flex`, it no longer does that. It behaves more like an inline element or a floated element, where its size is based on the size of its content.

So in your case, you have a flex container whose width is no longer known, and then you have your `.box` items inside of that and have their flex values set to `1 1 0%`. It seems like IE is having trouble sizing items because their size is dependent of the size of their container, which is in turn dependent on the size of its items.

The solution is to avoid this circularity completely. If you add `width: 100%` to your `#main` and `.ieee` elements, the sizes become definite, the circularity goes away, and everything renders just fine in IE.

Here's an example:
https://jsbin.com/funirukemo/1/edit?html,output
