### ISSUE TITLE
IE11 flex with min-height will not center nested elements

### ISSUE THREAD

**Issue by benfrain** [philipwalton/flexbugs#64]
**Issue**: In IE11 (not tested IE10 yet) any flex container with a min-height (px or %) set will not center it's child elements. This happens regardless of box-sizing models used.

Reduction: http://codepen.io/benfrain/pen/jPYpEw

I know there are a few min-height issues knocking around with regards to IE but they seem to relate to columns. Keen to get @gregwhitworth input on this

**Comment by philipwalton** [comment]
I definitely think this is related to [Flexbug 3](https://github.com/philipwalton/flexbugs#3-min-height-on-a-column-flex-container-wont-apply-to-its-flex-items). In both cases it seems like the flex items have no idea how tall their parent is, so doing things like flexing to fit or vertical centering is impossible since there's nothing to base those calculations off of.

Perhaps the bug could be reworded to be more inclusive of cases like this.

**Comment by gregwhitworth** [comment]
Agreed, it's the same as 3.

**Comment by benfrain** [comment]
Well, I think it's worth amending the wording on that one as it implies it only relates to flex columns. It actually relates to any flex container using min-height on IE10/11.

In many use cases this can also be worked around by setting the min-height and align-items: center on the child element (and not on the parent). That way min-height works as expected in IE 10/11.

**Comment by philipwalton** [comment]
@benfrain I removed mention of the column direction in 810ddb4123f5d5fac1291cdd4c33b7aa5403dfbd.

In addition, I was playing with your suggested workaround:

> In many use cases this can also be worked around by setting the min-height and align-items: center on the child element (and not on the parent).

At first this didn't make sense to me because if you apply to `min-height` and `align-items` to the item, wouldn't you just have the same problem because now the item is itself a container? But then I realized the bug seems to only happen to flex containers that are not themselves flex items.

I'm going to investigate a bit further, but I think this trick may serve as a fool-proof workaround for the `min-height` bug.

**Comment by philipwalton** [comment]
I added the new workaround in 306eebb50d2d66f8845c3ad063d4e2a0001c992b.

@gregwhitworth it'd be great if you could take a look, but I think this is pretty solid.

**Comment by FerchoCarcho** [comment]
Hello. I have an issue reggarding flexbox, min-height and vertically align items :center read [here](http://stackoverflow.com/questions/40267164/min-height100-along-with-flexbox-s-align-items-center-doesnt-make-items-vert) please.

**Comment by mgibas** [comment]
setting `height: 1px;`  along with `min-height` seems to fix the issue in IE11 without additional wrappers
