### ISSUE TITLE
flex-wrap: wrap and causes flex item's size to be 0 when it has element with percentage padding

### ISSUE THREAD

**Issue by safareli** [philipwalton/flexbugs#86]
When flex container's `flex-wrap` is set to `wrap`, flex item's size is 0 if it has element with percentage padding

http://codepen.io/safareli/pen/Oyprdr?editors=100

**Comment by philipwalton** [comment]
Hmmm, yeah this is probably a bug. I'm not really sure if there's a good workaround though.

**Comment by safareli** [comment]
problem is when percentage padding is on direction of flex container:
top, bottom on column and left, right on row.

so for example you can use percentage value for padding-[top | bottom] when flex-direction is row
but not for padding-[left | right]

**Comment by philipwalton** [comment]
Yeah, I'd recommend filing a bug with the affected browser vendors, and if you do please link to those bugs here so others can find them. I'm going to close this for now because I don't think there's a workaround, but feel free to reopen and recommend one.

**Comment by safareli** [comment]
just reported:
- https://code.google.com/p/chromium/issues/detail?id=548350
- https://bugs.webkit.org/show_bug.cgi?id=150601
- https://bugzilla.mozilla.org/show_bug.cgi?id=1218985

**Comment by dholbert** [comment]
I think Firefox's behavior is correct on the codepen here.  Basically, it's a question of whether the flex item's cross-size (its width, in this case) is considered "definite" & valid for percent resolution.

The flexbox spec has a [special case](https://drafts.csswg.org/css-flexbox-1/#definite-sizes) for stretched flex items in a "*single-line* flex container [with] a definite cross size".  But that special-case doesn't apply to multi-line flex containers.

Intuitively, those flex items should not be considered as having a definite cross-size, because their contents influence how many lines there are & hence can influence the amount of cross-size that they have available to them.

See my comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1218985#c1 for more details (or a different wording of these same thoughts).

**Comment by safareli** [comment]
I have tried to use [suitcss/components-flex-embed](https://github.com/suitcss/components-flex-embe) in flex box and thats why I had this isssue, so one should be crefull with percentage padding in flex layout. 

for brief explination by @dholbert see https://bugzilla.mozilla.org/show_bug.cgi?id=1218985#c5

**Comment by philipwalton** [comment]
> one should be crefull with percentage padding in flex layout.

Agreed, and I'd argue one should probably avoid using percentage margin/padding in any situation where the corresponding size isn't definite.

**Comment by safareli** [comment]
I think there should be "gotchas" section in here :d

**Comment by philipwalton** [comment]
Not a bad idea. If I get some time, and can come up with a few examples, maybe I'll add a section.

**Comment by alexplusde** [comment]
Isn't it the same as in:
https://bugzilla.mozilla.org/show_bug.cgi?id=958714

Looks like the spec allows two different ways of calculating padding with percentages.

**Comment by dholbert** [comment]
No, it's not.

The bug / spec-freedom you're referencing is about percentage padding *on flex items* (i.e. when the parent of the percent-padded thing is a flex container).

But, this issue here is about a case with percentage padding on a *child* of a flex item. Here, the parent of the percent-padded thing is a *block*, not a flex container.  (The grandparent of the percent-padded thing happens to be a flex container, but that doesn't matter for percent-resolution of the padding itself).

See my comment above for why this actually gets weird (due to ordering of sizing/resolution).
