### ISSUE TITLE
Horizontal scrollbar in flex column

### ISSUE THREAD

**Issue by gomoto** [philipwalton/flexbugs#91]
I'm coming across the following flexbug in Chrome 45 and 46 (but weirdly not in Chrome 46 in OSX 10.11.1). It's not an issue in Firefox; unsure about IE.

When a horizontally scrolling item in a flex column is hidden then shown, it is repainted without making room for the scrollbar. If the window is then resized, the item makes room for the scrollbar.

[The flexbug is demonstrated here.](//jsfiddle.net/qxu4akqr/)

Any thoughts on why this is happening or how to fix it? Thanks!

**Comment by philipwalton** [comment]
Hmmm, I'm on my Mac now, so I can't reproduce the bug, but it sounds like it's probably an issue with Chrome rather than Flexbox, especially if it's inconsistent between Chrome versions and platforms.

Can you report it on [chromium.org](http://www.chromium.org/for-testers/bug-reporting-guidelines) and then update this issue with the bug link?
